### ISSUE TITLE
Translating: japanese.json

### ISSUE THREAD

**Issue by eosjapan** [GetScatter/DesktopTranslations#2]
✋

**Comment by felixdragon** [comment]
I didn't realize you have already raised your hand to translate it into Japanese until I completed Japanese string.  Just in case if you have not yet finished, you may use the string below.
[japanese_json.zip](https://github.com/GetScatter/DesktopTranslations/files/2753787/japanese_json.zip)

**Comment by nsjames** [comment]
Merged in japanese <3

**Comment by felixdragon** [comment]
Great!

**Comment by newbdez33** [comment]
Thanks!
