### ISSUE TITLE
Translating: swedish.json

### ISSUE THREAD

**Issue by ramijames** [GetScatter/DesktopTranslations#8]
Lennie

**Comment by hyp3rn01d** [comment]
{
  "name":"Swedish",

  "methods":[
    {"name":"plural_s", "args":"n = 1", "body":"return parseInt(n) === 1 ? '' : 's'"}
  ],

  "locales":{
    "generic_back":"Tillbaka",
    "generic_confirm":"Bekräfta",
    "generic_allow":"Godkänn",
    "generic_deny":"Neka",
    "generic_okay":"Ok",
    "generic_cancel":"Avbryt",
    "generic_open":"Öppna",
    "generic_yes":"Ja",
    "generic_no":"Nej",
    "generic_enable":"Aktivera",
    "generic_disable":"Avaktivera",
    "generic_select":"Markera",
    "generic_unselect":"Avmarkera",
    "generic_edit":"Redigera",
    "generic_add":"Lägg till",
    "generic_save":"Spara",
    "generic_new":"Nytt",
    "generic_delete":"Radera",
    "generic_remove":"Ta bort",
    "generic_remove_all":"Ta bort alla",
    "generic_copy":"Kopiera",
    "generic_import":"Importera",
    "generic_export":"Exportera",
    "generic_refresh":"Uppdatera",
    "generic_manage":"Hantera",
    "generic_private_key":"Privat nyckel",
    "generic_public_key":"Offentlig nyckel{nycklar}",
    "generic_keys":"Nyckel{Nycklar}",
    "generic_hide":"Göm",
    "generic_reveal":"Avslöja",
    "generic_tokens":"Token{plural_s}",
    "generic_network":"Nätverk{plural_}",
    "generic_blockchain":"Blockkedja{Blockkedjor}",
    "generic_contract":"Kontrakt{plural_s}",
    "generic_memo":"Memo",
    "generic_symbol":"Symbol",
    "generic_decimals":"Decimaler",
    "generic_password_or_phrase":"Lösenord eller säkerhets-fras",
    "generic_timestamp":"Tidsstämpel",
    "generic_chain_id":"Kedje ID",
    "generic_name":"Namn",
    "generic_account":"Konto{plural_n}",
    "generic_account_name":"Kontonamn",
    "generic_address":"Adress",
    "generic_search":"Sök",
    "generic_buy":"Köp",
    "generic_sell":"Sälj",
    "generic_buying":"Köper",
    "generic_selling":"Säljer",
    "generic_identity":"Identitet",
    "login_new_tit":"Du verkar ny här!",
    "login_new_sub":"Börja med att skapa ett lösenord som kommer att användas för att kryptera all din privata data. Välj ett säkert lösenord.",
    "login_new_password_lbl":"Välj ett lösenord",
    "login_new_password_plc":"Var säker på att du väljer ett säkert lösenord!",
    "login_new_password_confirm_lbl":"Skriv in lösenordet igen",
    "login_new_password_confirm_plc":"Dubbelt så bra.",
    "login_new_create_btn":"Nu kör vi!",
    "login_new_restore_backup_btn":"Jag vill återskapa från en säkerhetskopia",
    "login_existing_tit":"Välkommen tillbaka",
    "login_existing_password_plc":"Lösenord eller säkerhets-fras",
    "login_existing_reset_btn":"Jag behöver återställa mitt lösenord",
    "login_restore_tit":"Återskapa från säkerhetskopia",
    "login_restore_sub":"Om du har en säkerhetskopia för din Scatter kan du importera den här. \n        Du behöver fortfarande lösenordet för att låsa upp säkerhetskopian.",
    "login_restore_choose_btn":"Välj din säkerhetskopia",
    "login_restore_back_btn":"Gå tillbaka och starta om",
    "dashboard_keys_search_plc":"Sök nycklar",
    "dashboard_keys_add_keys":"Lägg till nycklar",
    "dashboard_keys_no_keys":"Vad väntar vi på?",
    "dashboard_keys_linked_accounts":"{x} länkat konto{länkade konton}",
    "dashboard_toolbars_send":"Skicka",
    "dashboard_toolbars_receive":"Ta emot",
    "dashboard_apps_search_plc":"Sök appar",
    "dashboard_apps_no_apps_tit":"Inga appar anslutna",
    "dashboard_apps_no_apps_desc":"Du kan utforska appar genom att använda sökfältet här ovanför.",
    "dashboard_apps_link_perm_only":"Endast länkade behörigheter",
    "dashboard_apps_n_permissions":"{x} behörighet{behörigheter}",
    "dashboard_apps_no_permissions":"Inga behörigheter",
    "dashboard_apps_unlinked_apps_tit":"Nedanför ser du apparna du inte är ansluten till.",
    "dashboard_apps_unlinked_apps_sub":"Obs. Dessa appar är inte tillagda av Scatterteamet, utan av apparna själva. Ingen app som visas är en särskild rekommendation utan bara en sökfunktion.",
    "dashboard_apps_no_meta":"Ingen Meta",
    "add_keys_select_disclaimer":"Privata nycklar skapas lokalt på din dator och kommer aldrig i kontakt med internet.",
    "add_keys_select_create_tit":"Skapa en ny nyckel",
    "add_keys_select_create_desc":"Om du vill skapa en ny grupp nycklar du kan använda med valfri blockkedja. Nycklarna kommer inte att innehålla några tillgångar och är helt nya.",
    "add_keys_select_create_btn":"Skapa nyckel",
    "add_keys_select_import_tit":"Importera en befintlig nyckel",
    "add_keys_select_import_desc":"Om du redan har en nyckel och vill importera den till Scatter",
    "add_keys_select_import_btn":"Importera nyckel",
    "add_keys_select_create_eos_tit":"Skapa ett nytt EOS-konto",
    "add_keys_select_create_eos_desc":"Två nycklar skapas snabbt för dig",
    "add_keys_select_create_eos_btn":"EOS-konto",
    "add_keys_import_name_lbl":"Nyckelnamn",
    "add_keys_import_name_plc":"Ge nyckeln ett namn för att komma ihåg.",
    "add_keys_import_text_tit":"Importera privat nyckel som text",
    "add_keys_import_text_desc":"Om du vill skriva in eller klistra in din privata nyckel",
    "add_keys_import_text_btn":"Text",
    "add_keys_import_hw_tit":"Importera från en hårdvaru-plånbok",
    "add_keys_import_hw_desc":"Om du har en hårdvaru-plånbok som stöds",
    "add_keys_import_hw_btn":"Hårdvara",
    "add_keys_import_qt_tit":"Importera privat nyckel från en QR-kod",
    "add_keys_import_qr_desc":"Om du har en krypterad pappers-plånbok eller en QR-kod",
    "add_keys_import_qr_btn":"QR",
    "add_keys_import_text_key_lbl":"Skriv in privat nyckel",
    "add_keys_import_text_key_plc":"Försäkra dig om att du skriver rätt",
    "add_keys_import_text_errors_invalid_key_len":"Privat nyckel inte tillräckligt lång ({x})",
    "add_keys_import_hw_sel_hard_lbl":"Välj en hårdvaru-plånbok",
    "add_keys_import_hw_avail_blok_lbl":"Tillgängliga blockkedjor",
    "add_keys_import_hw_idx_lbl":"Nyckel/Adress-index",
    "add_keys_import_hw_hw_err":"Hårdvarufel",
    "add_keys_import_hw_unlock_ledger_err":"Du behöver låsa upp din Ledger och öppna {x} Ledger App.",
    "add_keys_import_hw_unlock_liq_eos_err":"Du behöver låsa upp din Liquid EOS hardware wallet.",
    "add_keys_eos_keys_owner_desc":"Det här är din huvudnyckel som kontrollerar ditt konto. Ha inte huvudnyckeln i Scatter om du inte absolut måste det.",
    "add_keys_eos_keys_active_desc":"Det här är nyckeln du kommer att använda med appar. Det är den du vill ha importerad till Scatter.",
    "add_keys_eos_keys_create_eos_acc_tit":"Använd de här nycklarna för att skapa ett EOS-konto.",
    "add_keys_eos_keys_create_eos_acc_desc":"Du kan inte omedelbart använda EOS med bara nycklar, du behöver skapa ett konto med dem.",
    "add_keys_eos_keys_create_eos_acc_btn":"Skapa konto",
    "create_eos_disc_tit":"Konton på EOS-blockkedjan måste betalas för att kunna användas.",
    "create_eos_acc_name_len_err":"Kontonamnet måste vara 12 tecken långt.",
    "create_eos_acc_name_form_err":"Kontonamnet får bara innehålla små bokstäver.",
    "create_eos_sel_creator_err":"Välj kontots skapare först.",
    "create_eos_check_name_alert":"Kollar om namnet är tillgängligt...",
    "create_eos_name_taken_alert":"Det här namnet är redan taget.",
    "create_eos_account_acc_lbl":"Det här kontot kommer att användas för att skapa kontot",
    "create_eos_account_ram_cost_lbl":"Obligatorisk kostnad för RAM",
    "create_eos_account_resources_lbl":"CPU och NET",
    "create_eos_account_res_low_err":"Du måste tilldela minst {x}",
    "create_eos_account_total_lbl":"Totalt",
    "create_eos_account_act_bar_btn":"Skapa konto",
    "create_eos_exchange_change_name":"Vill du ändra namn?",
    "create_eos_exchange_info_tit":"Du behöver betala för de resurser som används för att skapa konton på EOS-blockkedjan.",
    "create_eos_exchange_info_sub":"Alla extra medel du skickar kommer att överföras till kontot.",
    "create_eos_exchange_use_name_btn":"Använd namn",
    "create_eos_exchange_ex_field_parts":[
      "Skicka åtminstone",
      "till konto",
      "med",
      "som memo"
    ],
    "create_eos_exchange_sent_tit":"Efter att du har skickat EOS från en exchange enligt detaljerna ovan, kopiera in transaktions-ID här.",
    "create_eos_exchange_sent_sub":"Du måste vänta tills transaktionen är oåterkallelig, det tar cirka 3 minuter.",
    "create_eos_exchange_tx_id_lbl":"Transaktions-ID",
    "create_eos_exchange_act_bar_btn":"Skapa konto",
    "create_eos_errors_invalid_res":"CPU eller NET var under eller lika med 0",
    "keypair_name_lbl":"Nyckelnamn",
    "keypair_name_plc":"Ge nyckeln ett namn för att komma ihåg.",
    "keypair_dashboard_states_add":"Lägg till konto",
    "keypair_dashboard_states_linked":"Länkade konton",
    "keypair_dashboard_states_keys":"Nycklar och Blockkedjor",
    "keypair_dashboard_add_account_create_eos_lbl":"Skapa ett nytt EOS-konto",
    "keypair_dashboard_add_account_create_eos_desc":"Om du vill skapa ett nytt EOS-konto ovanpå den här nyckeln.",
    "keypair_dashboard_add_account_create_eos_btn":"Skapa konto",
    "keypair_dashboard_add_account_link_eos_lbl":"Länka befintligt EOS-konto",
    "keypair_dashboard_add_account_link_eos_desc":"Om du redan har ett EOS-konto, men det inte importeras automatiskt.",
    "keypair_dashboard_add_account_net_acc_lbl":"Länka befintligt EOS-konto",
    "keypair_dashboard_errors_invalid_wallet_name":"Skriv in ett namn för den här nyckeln",
    "keypair_dashboard_errors_wallet_name_exists":"En nyckel med det här namnet finns redan",
    "keypair_tokens_hidden_tokens":"{x} tokens filtrerade av ditt token spam-filter.",
    "keypair_tokens_search_tokens":"Sök tokens",
    "keypair_accounts_search_plc":"Sök konton",
    "keypair_accounts_view_tokens":"{x} Token{plural_s}",
    "keypair_accounts_eos_refund_btn":"Återbetalning",
    "keypair_accounts_eos_danger_perms":"Aktiv och ägare har båda samma nyckel.",
    "keypair_accounts_eos_danger_perms_sub":"Överväg att byta en nyckel till en annan genom att klicka \"Ändra behörigheter\" -knappen här nedanför.",
    "keypair_accounts_actions_eos_change_perms_btn":"Ändra behörigheter",
    "keypair_accounts_actions_eos_proxy_votes_btn":"Proxy-röster",
    "keypair_accounts_actions_eos_unlink_acc_btn":"Avlänka konto",
    "keypair_blockchains_cpy_btn":"Kopiera offentlig nyckel",
    "keypair_export_select_key_tit":"Nyckel",
    "keypair_export_select_key_desc":"Exportera nyckeln som text",
    "keypair_export_select_qr_tit":"Pappers-plånbok",
    "keypair_export_select_qr_desc":"Exportera den här privata nyckeln som en krypterad QR-kod",
    "keypair_export_key_key_tit":"Privat nyckel som text",
    "keypair_export_key_copy_btn":"Kopiera",
    "keypair_export_key_reveal_btn":"Avslöja",
    "keypair_export_key_hide_btn":"Göm",
    "keypair_export_qr_qr_tit":"Pappers-plånbok med QR-kod",
    "keypair_export_qr_save_btn":"Spara som bild",
    "identity_tit":"Identitet",
    "identity_disclaimer_tit_imp":"Inget här behövs för att använda Scatter",
    "identity_disclaimer_tit":"men det kan krävas av appar som ansluter till din Scatter, t.ex. när du använder en shopping-app som behöver din adress.",
    "identity_disclaimer_sub":"All information sparas lokalt på din dator och skickas aldrig någonstans utan ditt medgivande.",
    "identity_name_lbl":"Identitetens namn / användarnamn",
    "identity_name_plc":"Din online-närvaro",
    "identity_name_err":"Identitetens namn kan inte lämnas tomt, innehålla ordmellanrum eller specialtecken.",
    "identity_personal_name_lbl":"Fullständigt namn",
    "identity_personal_name_plc":"Skriv in ditt fullständiga namn",
    "identity_personal_dob_lbl":"Födelsedatum",
    "identity_personal_email_lbl":"Epost",
    "identity_location_disclaimer_tit":"Du kan skapa flera platser.",
    "identity_location_disclaimer_sub":"T.ex. \"Hemma\" och \"Arbetet\". Du kommer att kunna välja den du vill använda när du behöver det.",
    "identity_location_sel_lbl":"Platser",
    "identity_location_sel_add_button":"Lägg till",
    "identity_location_name_lbl":"Namn på plats",
    "identity_location_name_plc":"Hem",
    "identity_location_name_err":"Namn på platser kan inte lämnas tomma.",
    "identity_location_country_lbl":"Land",
    "identity_location_country_item_none":"Inget",
    "identity_location_phone_lbl":"Telefonnummer",
    "identity_location_phone_plc_a":"555",
    "identity_location_phone_plc_b":"555",
    "identity_location_phone_plc_c":"5555",
    "identity_location_adr_lbl":"Adress",
    "identity_location_adr_plc":"5 Broadway",
    "identity_location_city_lbl":"Stad",
    "identity_location_city_plc":"New York",
    "identity_location_state_lbl":"State",
    "identity_location_state_plc":"NY",
    "permissions_list_lbl":"Rättigheter",
    "permissions_login_perm":"Login-rättigheter",
    "permissions_accounts_lbl":"Inlagda konton",
    "permissions_req_fields_lbl":"Obligatoriska fält",
    "permissions_mutable_fields_lbl":"Varierande fält",
    "permissions_rem_lbl":"Ta bort rättigheter",
    "permissions_rem_id_lbl":"Login-rättigheter är det som låter appar interagera med ditt Scatter. Du kan tvångsavsluta en app genom att ta bort rättigheterna.",
    "permissions_rem_white_lbl":"Action whitelists gör att du inte ständigt behöver acceptera popups för att signera transaktioner. Vill du ta bort denna whitelist?",
    "permissions_act_whitelist":"Action whitelist",
    "settings_basics":"Grundläggande",
    "settings_danger_zone":"Riskzon",
    "settings_menu_general":"Allmänt",
    "settings_menu_language":"Språk",
    "settings_menu_tokens":"Tokens",
    "settings_menu_explorers":"Utforskare",
    "settings_menu_pin":"PIN-kod",
    "settings_menu_firewall":"Brandvägg",
    "settings_menu_networks":"Nätverk",
    "settings_menu_password":"Lösenord",
    "settings_menu_backup":"Säkerhetskopia",
    "settings_menu_destroy":"Förstör",
    "settings_general_version_lbl":"Version",
    "settings_general_update_avail":"Uppdatering tillgänglig",
    "settings_general_no_update_avail":"Ingen uppdatering tillgänglig",
    "settings_general_white_noti_lbl":"Whitelist-notiser",
    "settings_general_white_noti_desc":"Dessa notiser syns på somliga operativsystem när du auto-signerar whitelistade transaktioner.",
    "settings_general_data_path_lbl":"Sökväg för data",
    "settings_general_data_path_desc":"Platsen på din dator där Scatter sparar din krypterade data.",
    "settings_general_dev_console_lbl":"Stöd till utvecklare",
    "settings_general_dev_console_desc":"Ibland behöver du kanske se efter om Scatter ger några felmeddelanden.",
    "settings_general_dev_console_btn":"Öppna stöd",
    "settings_language_lbl":"Välj språk",
    "settings_tokens_switch_add_token":"Lägg till token",
    "settings_tokens_switch_whitelist":"Tokens",
    "settings_tokens_switch_blacklist":"Filtrerat",
    "settings_tokens_switch_settings":"Inställningar",
    "settings_tokens_add_token_disclaimer":"Lägger du till tokens kan du skicka dem och hämta saldo.",
    "settings_tokens_add_token_tok_name_plc":"Namnge denna token eller lämna tomt för att använda dess börssymbol.",
    "settings_tokens_add_token_tok_name_lbl":"Tokennamn",
    "settings_tokens_add_token_white_tok_btn":"Whitelista token",
    "settings_tokens_add_token_black_tok_btn":"Blacklista token",
    "settings_tokens_settings_main_bal_dis_lbl":"Huvud-saldo display",
    "settings_tokens_settings_main_bal_dis_desc":"Du kan välja om du vill se saldot för alla nätverk i panelen, eller bara saldot för huvudnätverk.",
    "settings_tokens_settings_main_bal_dis_main_btn":"Visa alla nätverk",
    "settings_tokens_settings_main_bal_dis_main_desc":"Om bara tokens på huvudnätverket visas kommer Scatter inte använda alternativa kedjors tokens eller tokens på testnät för att räkna ut det totala saldot.",
    "settings_tokens_settings_main_bal_dis_all_btn":"Visa bara huvudnätverk",
    "settings_tokens_settings_main_bal_dis_all_desc":"Visas alla nätverk kommer Scatter använda alla nätverk för att räkna ut det totala saldot.",
    "settings_tokens_settings_filter_small_bal_lbl":"Filtrera små summor",
    "settings_tokens_settings_filter_small_bal_desc":"Om du alltid vill filtrera tokens med små belopp kan du modifiera det här.",
    "settings_tokens_white_black_tok_filter_lbl":"Filtrera tokens i olika blockkedjor",
    "settings_tokens_white_black_tok_search_plc":"Sök tokens",
    "settings_tokens_white_black_whitelist_disclaimer":"Välj en token eller valuta för att göra den till din din förvalda displaytyp.",
    "settings_tokens_white_black_whitelist_fiat_curr_lbl":"Visa som fiat-valuta",
    "settings_tokens_white_black_whitelist_sys_tok_lbl":"System-tokens",
    "settings_tokens_white_black_whitelist_cus_tok_lbl":"Anpassade tokens",
    "settings_tokens_white_black_blacklist_disclaimer":"Du kan inte filtrera bort system-tokens för dina nätverk.",
    "settings_pin_label":"Ändra PIN-kod",
    "settings_pin_desc":"Din PIN-kod är ett sekundärt internt lösenord för att göra transaktioner.",
    "settings_pin_desc_red":"Ha inte samma PIN-kod som ditt lösenord!",
    "settings_pin_placeholder":"PIN-kod avaktiverad",
    "settings_pin_save_snack":"Sparad PIN-kod",
    "settings_pin_pin_4_all_tit":"Använd PIN-kod för all interaktion.",
    "settings_pin_pin_4_all_desc":"Om du aktiverar kommer du att behöva skriva in din PIN-kod för varje popup.",
    "settings_networks_switch_known":"Kända nätverk",
    "settings_networks_switch_custom":"Dina nätverk",
    "settings_networks_known_add_label":"Lägg till ett känt nätverk",
    "settings_networks_known_add_desc":"Blockchain-nätverk med många användare kan enkelt läggas till utan att skriva in detaljerna manuellt.",
    "settings_networks_custom_name_plc":"Lokalt nätverk",
    "settings_networks_custom_host_lbl":"Värd ( domän.com eller IP )",
    "settings_networks_custom_proto_lbl":"Protokoll",
    "settings_networks_custom_port_lbl":"Port",
    "settings_networks_custom_chain_id_tool":"Hämta kedje-ID",
    "settings_networks_custom_from_origin_plc":"Ursprung",
    "settings_networks_custom_cus_sys_tok_lbl":"Anpassad system-token",
    "settings_networks_custom_cus_sys_tok_desc":"I somliga fall kan system-token behöva ändras.",
    "settings_networks_custom_cus_sys_tok_def_btn":"Använd förinställd system-token",
    "settings_networks_custom_cus_sys_tok_use_cus_btn":"Använd anpassad system-token",
    "settings_networks_custom_using_cus_sys_tok":"Det här nätverket använder en anpassad system-token.",
    "settings_password_cng_pass_lbl":"Ändra ditt lösenord",
    "settings_password_cng_pass_desc":"Varje gång du ändrar ditt lösenord får du en mnemoteknisk säkerhets-fras som är ditt alternativa lösenord för att låsa upp Scatter.",
    "settings_password_new_pass_lbl":"Nytt lösenord",
    "settings_password_new_pass_plc":"Lösenord",
    "settings_password_conf_pass_lbl":"Bekräfta nytt lösenord",
    "settings_password_conf_pass_plc":"Skriv in lösenordet igen",
    "settings_password_cng_pass_btn":"Ändra lösenord",
    "settings_password_view_mne_lbl":"Visa mnemoteknisk fras",
    "settings_password_view_mne_desc":"Om du har tappat bort ditt lösenords mnemotekniska säkerhets-fras kan du se den här.",
    "settings_password_view_mne_btn":"Visa mnemoteknisk fras",
    "settings_password_changed_pass_snack":"Lösenord ändrat",
    "settings_backup_lbl":"Konfigurera säkerhetskopia",
    "settings_backup_desc":"Säkerhetskopior låter dig spara hela ditt Scatter inklusive alla nycklar, rättigheter och inställningar.",
    "settings_backup_auto_backup_lbl":"Plats för automatisk säkerhetskopia",
    "settings_backup_create_backup_btn":"Skapa säkerhetskopia",
    "settings_backup_curr_backup_lbl":"Nuvarande folder för säkerhetskopia",
    "settings_firewall_enabled_lbl":"Aktivera brandvägg",
    "settings_firewall_enabled_desc":"RIDL Defender är Scatters egna decentraliserade brandväggs-system. Det skyddar dig mot skadliga web-sidor, appar och konton.",
    "settings_destroy_lbl":"Konfigurera",
    "settings_destroy_desc":"Förstör Scatter kommer att ta bort all din data inklusive identiteter och konfigurerade nyckelpar från din lokala maskin. Det kommer inte att radera dina konton från själva blockkedjan.",
    "settings_destroy_imp":"FÖRSÄKRA DIG OM ATT DU VERKLIGEN HAR EN SÄKERHETSKOPIA INNAN DU GÖR DET HÄR!",
    "settings_destroy_btn":"Förstör Scatter",
    "transfer_send_btn":"Skicka",
    "transfer_from_from_lbl":"Från",
    "transfer_from_send_acc_lbl":"Avsändarkonto",
    "transfer_tokens_amount_lbl":"Belopp att överföra",
    "transfer_tokens_cus_tok_lbl":"Anpassad token",
    "transfer_tokens_save_tok_btn":"Spara token",
    "transfer_recipient_rec_lbl":"Mottagare",
    "transfer_recipient_send_to_contact":"Kontakter",
    "transfer_recipient_send_directly":"Direkt",
    "transfer_recipient_send_self":"Eget",
    "transfer_recipient_search_contacts_plc":"Sök kontakter",
    "transfer_recipient_search_self_plc":"Sök konton",
    "transfer_recipient_contacts_lbl":"Kontakter",
    "transfer_recipient_verify_recipient":"Kolla en gång till",
    "transfer_recipient_contact_name_plc":"Namn på kontakt",
    "transfer_recipient_contact_name_lbl":"Vill du lägga till {x} som en kontakt?",
    "transfer_errors_invalid_rec":"Ogiltig mottagare",
    "transfer_errors_invalid_amnt":"Ogiltigt belopp, måste vara större än 0",
    "user_bar_manage_id":"Hantera identitet",
    "processes_fetch_acc_net":"Hämtar konton för {x}",
    "processes_import_acc_net":"Importerar konton för {x}",
    "processes_imp_accs":"Importerar konton",
    "processes_load_res":"Laddar tillgångar",
    "processes_acc_left":"Konton som återstår: {x}",
    "snackbar_cop_to_clip":"Kopierat till urklipp",
    "snackbar_bad_pass":"Svagt lösenord",
    "snackbar_saved_img":"Bild sparad",
    "snackbar_token_added":"Token tillagd",
    "snackbar_cont_exists":"En annan kontakt har redan den här mottagaren",
    "snackbar_cont_name_exists":"En annan kontakt har redan det här namnet",
    "snackbar_network_miss_name":"Nätverket måste ha ett namn",
    "snackbar_network_miss_host":"Nätverket måste ha en värd",
    "snackbar_network_miss_port":"Nätverket måste ha en giltig port",
    "snackbar_network_miss_chain":"Nätverket måste ha ett kedje-ID",
    "snackbar_network_chain_exists":"Ett nätverk med samma kedje-ID finns redan",
    "snackbar_network_name_exists":"Ett nätverk med det här namnet finns redan",
    "snackbar_network_saved":"Nätverk sparat!",
    "snackbar_network_deleted":"Nätverk raderat!",
    "snackbar_tokens_miss_symbol":"Du måste lägga till en token-symbol",
    "snackbar_tokens_miss_contract":"Du måste lägga till ett token-kontrakt",
    "snackbar_tokens_exists_added":"Denna token finns redan bland tillagda tokens",
    "snackbar_tokens_exists_filtered":"Denna token finns redan bland filtrerade tokens",
    "snackbar_auth_locked_out":"Du har blivit tillfälligt avstängd",
    "snackbar_auth_err_parse_backup":"Misslyckad diagnos av säkerhetskopia",
    "snackbar_auth_err_decr_backup":"Misslyckad avkryptering av säkerhetskopia",
    "snackbar_auth_cant_read_backup":"Säkerhetskopia kan inte läsas",
    "snackbar_auth_pass_len":"Lösenord måste vara minst 8 tecken långa",
    "snackbar_auth_bad_conf":"Bekräftelse matchar inte lösenordet",
    "popouts_req_fields_per_info":"Personlig info",
    "popouts_req_fields_loc_info":"Platsinfo",
    "popouts_login_acc_reqs":"Appen kräver konton för dessa nätverk",
    "popouts_login_no_accs_tit":"Du har inte blockkedje-konton för nätverken som den här appen använder.",
    "popouts_login_no_accs_desc":"Innan du loggar in i den här appen, gå tillbaka till Scatter och importera några nycklar för nätverket/blockkedjan som den här appen använder.",
    "popouts_login_miss_fields_tit":"Några fält saknas!",
    "popouts_login_miss_fields_desc":"Fyll i nedan för att lägga till fälten till din identitet för senare användning och för att återföra dem till appen.",
    "popouts_login_login_btn":"Inloggning",
    "popouts_login_show_all_accs":"Visa alla",
    "popouts_login_filter_accs":"Filtrera",
    "popouts_get_key_gen_key_btn":"Skapa en ny nyckel",
    "popouts_get_key_search_plc":"Sök nycklar",
    "popouts_link_app_app_key":"App-nyckel",
    "popouts_link_app_disclaimer":"Försäkra dig om att appens namn är den app du använder just nu.",
    "popouts_signature_acts_total":"{x} åtgärder totalt",
    "popouts_signature_accs_involved":"Inblandade konton",
    "popouts_signature_keys_involved":"Inblandade nycklar",
    "popouts_signature_arb_dis_tit":"Arbiträr signering inaktiverad!",
    "popouts_signature_arb_dis_desc":"För att skydda dig har vi stängt av möjligheten att signera arbiträr data som är längre än 12 tecken per ord.",
    "popouts_signature_whitelist_desc":"Whitelista detta för att inte behöva godkänna nästa gång",
    "popouts_signature_dis_white_btn":"Avaktivera whitelist",
    "popouts_signature_enbl_white_btn":"Aktivera whitelist",
    "popouts_signature_prev_whitelist":"Den här åtgärden var tidigare whitelistad.",
    "popouts_signature_hid_act":"Åtgärden är dold",
    "popouts_transfer_sending_to":"skickar {x} till",
    "popouts_transfer_search_plc":"Sök konton",
    "popins_fullscreen_check_hardware_tit":"Kolla hårdvara",
    "popins_fullscreen_check_hardware_desc":"Du bör se en bekräftelse på din hårdvaru-device.",
    "popins_fullscreen_confirm_pass_tit":"Bekräfta lösenord",
    "popins_fullscreen_confirm_pass_lbl":"Skriv in lösenord eller backup-fras",
    "popins_fullscreen_destroy_tit":"Förstör Scatter",
    "popins_fullscreen_destroy_disc":"Innan du gör det här, försäkra dig om att alla dina privata nycklar är säkerhetskopierade.",
    "popins_fullscreen_destroy_desc":"Förstör Scatter är oåterkalleligt, och du kommer inte att kunna återskapa någon data utan säkerhetskopia.",
    "popins_fullscreen_whitelisting_tit":"Aktiverad Whitelist",
    "popins_fullscreen_whitelisting_desc":"Whitelistade åtgärder gör att du inte behöver fortsätta godkänna åtgärder för appar du litar på. När du whitelistar åtgärder kommer du att se kryssrutor bredvid varje varje åtgärd och värde.",
    "popins_fullscreen_whitelisting_act_lbl":"Denna åtgärd kommer att whitelistas",
    "popins_fullscreen_whitelisting_mutable_prop":"Detta värde kommer att kunna ändras utan en popup",
    "popins_fullscreen_whitelisting_immutable_prop":"om detta ändras kommer du att behöva godkänna åtgärden igen",
    "popins_fullscreen_eos_available":"Tillgängligt {x}",
    "popins_fullscreen_eos_reclaim":"Återtar {x}",
    "popins_fullscreen_eos_change_perms_tit":"Ändra konto-behörigheter",
    "popins_fullscreen_eos_change_perms_desc":"När du ändrar ditt kontos behörigheter ändras nycklarna som kontrollerar kontot.",
    "popins_fullscreen_eos_change_perms_sub_desc":"Du kan lämna valfritt fält tomt för att behålla befintliga behörigheter.",
    "popins_fullscreen_eos_change_perms_keys_lbl":"Importerade nycklar",
    "popins_fullscreen_eos_change_perms_key_plc":"Skriv in en offentlig nyckel eller ett kontonamn",
    "popins_fullscreen_eos_change_perms_owner_lbl":"Ägare",
    "popins_fullscreen_eos_change_perms_active_lbl":"Aktiv",
    "popins_fullscreen_eos_change_perms_btn":"Ändra behörigheter",
    "popins_fullscreen_eos_mod_cpunet_stake":"Insats",
    "popins_fullscreen_eos_mod_cpunet_unstake":"Ta bort insats",
    "popins_fullscreen_eos_mod_cpunet_stake_desc":"Egen insats i CPU & NET ger det här kontot mer användbart på blockkedjan.",
    "popins_fullscreen_eos_mod_cpunet_unstake_desc":"Att ta bort insats i CPU & NET returnerar tokens, men försämrar kontots användbarhet.",
    "popins_fullscreen_eos_mod_ram_buy_desc":"Att köpa RAM gör att kontot kan innehålla mer data på blockkedjan.",
    "popins_fullscreen_eos_mod_ram_sell_desc":"Att sälja RAM returnerar tokens till kontot med beloppet motsvarande aktuellt pris på RAM.",
    "popins_fullscreen_eos_mod_ram_bytes_err":"Bytes måste vara fler än 15",
    "popins_fullscreen_eos_proxy_tit":"Proxy-röster",
    "popins_fullscreen_eos_proxy_repro_tit":"Vill du automatiskt proxy-rösta var sjunde dag?",
    "popins_fullscreen_eos_proxy_repro_desc":"Aktiverar du detta och godkänner en första transaktion kommer alla framtida transaktioner också att godkännas.",
    "popins_fullscreen_eos_proxy_lbl":"Proxy",
    "popins_fullscreen_eos_proxy_plc":"Skriv in en kontonamnet för en proxy",
    "popins_fullscreen_eos_proxy_known_prox_lbl":"Kända proxies",
    "popins_fullscreen_eos_proxy_btn":"Ställ in proxy",
    "popins_fullscreen_mnemonic_tit":"Lösenords-alternativ",
    "popins_fullscreen_mnemonic_desc":"Den här frasen är en säkerhetskopia på ditt lösenord. Den används inte för att skapa nycklar.",
    "popins_fullscreen_mnemonic_sub_desc":"Du kan klistra in den här frasen i valfritt fält som accepterar ett lösenord i Scatter.",
    "popins_fullscreen_remove_key_tit":"Ta bort nycklar",
    "popins_fullscreen_remove_key_disc":"Att ta bort nycklar tar också bort alla tillhörande konton och deras behörigheter för appar.",
    "popins_fullscreen_remove_location_tit":"Tar bort plats",
    "popins_fullscreen_unlink_account_tit":"Avlänka konton",
    "popins_fullscreen_unlink_account_desc":"Att ta bort ett länkat konto tar också bort dess behörigheter för appar.",
    "popins_fullscreen_unlink_account_sub_desc":"Välj den behörighet du vill ta bort.",
    "popins_fullscreen_unlink_account_auth_lbl":"Behörighet",
    "popins_fullscreen_unlink_blockchain_tit":"Avlänka blockkedja",
    "popins_fullscreen_unlink_blockchain_disc":"Att avlänka en blockkedja tar också bort alla dess konton och behörigheter för appar.",
    "popins_overlay_conf_pin":"Bekräfta PIN-kod",
    "popins_overlay_remove_app_tit":"Tar bort app",
    "popins_overlay_remove_app_desc":"Den här appen kommer att tas bort från din Scatter. Detta tar också bort alla whitelistade behörigheter.",
    "popins_overlay_trx_success_tit":"Transaktionen lyckades!",
    "popins_overlay_trx_success_desc":"Klicka länken nedan för att se i {x}",
    "popins_overlay_update_avail_tit":"Scatter-uppdatering tillgänglig",
    "popins_overlay_update_avail_click_link":"Klicka länken nedan för att komma till nedladdnings-sidan"
  }
}

**Comment by nsjames** [comment]
Closed and merged <3 
thanks
